version: 2
updates:
  - package-ecosystem: devcontainers
    directory: "/templates/src"
    schedule:
      interval: weekly
    labels: ["deps", "devcontainers", "templates"]

  - package-ecosystem: devcontainers
    directory: "/"
    schedule:
      interval: weekly
    labels: ["deps", "devcontainers"]
