#!/bin/sh
set -e

SET_AS_DEFAULT="${SETASDEFAULTSHELL:-"true"}"

TARGET_USER="${_REMOTE_USER:-}"

if [ -z "$TARGET_USER" ] || [ "$TARGET_USER" = "root" ]; then
  echo "ERROR: No non-root target user detected (_REMOTE_USER=[$_REMOTE_USER])."
  echo "       Add common-utils (installZsh=true) BEFORE this feature, or pass a username env to the build."
  exit 1
fi

if ! id -u "$TARGET_USER" >/dev/null 2>&1; then
  echo "ERROR: The specified remote user '$TARGET_USER' does not exist. Ensure common-utils ran first or set _REMOTE_USER. Aborting antidote installation."
  exit 1
fi

TARGET_HOME=$(eval echo "~$TARGET_USER")

# Respect ZDOTDIR if set for target user; else default to home
ZDOTDIR="${ZDOTDIR:-$TARGET_HOME}"
ANTIDOTE_DIR="$ZDOTDIR/.antidote"

# Require zsh and git
if ! command -v zsh >/dev/null 2>&1; then
  echo "ERROR: zsh not found. Install it (e.g., common-utils with installZsh=true) before this feature."
  exit 1
fi

GIT_BIN="$(command -v git || true)"
[ -n "$GIT_BIN" ] || { echo "ERROR: git not found. Install git feature or package before this feature."; exit 1; }

# Ensure dotfiles dir exists
install -d -m 755 "$ZDOTDIR"

# Install Antidote (clone if missing)
if [ ! -d "$ANTIDOTE_DIR/.git" ]; then
  su - "$TARGET_USER" -c "'$GIT_BIN' clone --depth=1 https://github.com/mattmc3/antidote '$ANTIDOTE_DIR'"
fi

# fast default plugins
PLUGS="$ZDOTDIR/.zsh_plugins.txt"
cat > "$PLUGS" <<'EOF'
zsh-users/zsh-autosuggestions
zdharma-continuum/fast-syntax-highlighting
zsh-users/zsh-completions
agkozak/zsh-z
EOF

# static bundle (performance)
su - "$TARGET_USER" -c "zsh -lc 'source $ANTIDOTE_DIR/antidote.zsh; antidote bundle < $PLUGS > $ZDOTDIR/.zsh_plugins.zsh'"

ZSHRC="$ZDOTDIR/.zshrc"
touch "$ZSHRC"

# inject into .zshrc if it doesn't exist yet
if ! grep -q '## BEGIN: antidote' "$ZSHRC"; then
  cat >> "$ZSHRC" <<'EOF'

## BEGIN: antidote
# Load pre-bundled plugins (generated by Antidote)
[ -f "${ZDOTDIR:-$HOME}/.zsh_plugins.zsh" ] && source "${ZDOTDIR:-$HOME}/.zsh_plugins.zsh"

# history and QoL
setopt hist_ignore_all_dups hist_reduce_blanks inc_append_history share_history
HISTFILE=${XDG_STATE_HOME:-$HOME/.local/state}/shell/zsh_history
SAVEHIST=200000
HISTSIZE=200000
mkdir -p -- "${HISTFILE:h}" 2>/dev/null || true
EOF
fi

# Fix ownership in case we ran as root
chown -R "$TARGET_USER":"$TARGET_USER" "$ZDOTDIR"

# optional: set zsh as default shell (when requested)
if [ "$SET_AS_DEFAULT" = "true" ]; then
  ZSH_PATH="$(command -v zsh || true)"
  if [ -n "$ZSH_PATH" ]; then
    if command -v chsh >/dev/null 2>&1; then
      chsh -s "$ZSH_PATH" "$TARGET_USER" || true
    else
      # Fallback: update /etc/passwd via usermod if available
      if command -v usermod >/dev/null 2>&1; then
        usermod -s "$ZSH_PATH" "$TARGET_USER" || true
      fi
    fi
  fi
fi
